### ISSUE TITLE
Importing IW3 weapons from cfgfactory to IW4

### ISSUE THREAD

**Issue by ghost** [TheApadayo/zonebuilder#1]
Is it possible to import custom models from cfgfactory.com for IW3 to IW4?
For example: http://cod4.cfgfactory.com/skins/show/53d788c73a66d
Thanks!

**Comment by TheApadayo** [comment]
Yes, but you need unreleased software (I didn't write it) for you to do that

**Comment by ghost** [comment]
I already have it, I just wasn't sure how to use it. Thanks!

**Comment by win32re** [comment]
@TheApadayo Can you please explain why can't I do it with ZoneBuilder?
