### ISSUE TITLE
Material Errors

### ISSUE THREAD

**Issue by FreeTheTech101** [TheApadayo/zonebuilder#10]
Well, it appears that after the lastest update that should have fixed the bug with material crashing has caused more crashes then it has fixed. Maybe revert the changes for now or move them to a new branch?

**Comment by iAmThatMichael** [comment]
The issue was noted when I finally managed to load it yesterday. Apadayo is now gone for a week so you can just revert back to a previous commit and give that a go until he can get it fixed.

**Comment by TheApadayo** [comment]
Don't use the most recent commit. I can guarantee that it isn't going to be stable. Don't expect it to be. Also don't believe commit logs, they always lie.
