### ISSUE TITLE
Normal Maps Not WORKING

### ISSUE THREAD

**Issue by 33arc** [TheApadayo/zonebuilder#11]
Normal Maps Not Working

**Comment by 33arc** [comment]
iw4tool's normal maps are working but zone builder's normal maps not working.

**Comment by TheApadayo** [comment]
care to elaborate a little bit about the issue? Are you using the new or old material format? How are you converting your normal map?
Also, I know for a fact that normal maps work.

**Comment by 33arc** [comment]
Sorry, I fixed it. I just wrote it wrong :/ 
////////////////////////////////////////////////////////////////////////
colorMap,mtl_t6_wpn_launch_mm1_nml
normalMap,mtl_t6_wpn_launch_mm1_col
specularMap,~gmtl_t6_wpn_launch_mm1_spc-r~c261ade3
