### ISSUE TITLE
Cannot open "buildnumber.h": No such file or directory

### ISSUE THREAD

**Issue by shit-ware** [TheApadayo/zonebuilder#12]
I was attempting to compile this tool in VS2013 and it could not include a header file. Is it an error on my part, or is there an issue with your end?
![error](https://cloud.githubusercontent.com/assets/10711154/8734038/eaa32d42-2bcc-11e5-848e-69dda0e24f0a.png)

**Comment by ghost** [comment]
Did you clone the repository with Git (git clone <repo url>) or just download it?
buildnumber.h is a file generated by a tool that uses Git.

**Comment by shit-ware** [comment]
Oh, that was fast! I downloaded it as a zip. So I should try using it via git clone?

**Comment by ghost** [comment]
Yep, make sure you have Git installed and that it's in your PATH variable.

**Comment by shit-ware** [comment]
Alright, awesome! It worked. Thanks for the help. Sorry for creating a fake issue. I should think through this stuff more often.

**Comment by ghost** [comment]
No problem :) Have a nice day!

**Comment by shit-ware** [comment]
Well, I have one more issue that will probably be easily solved. I can not find "zonebuilder.exe". It was not compiled and all I got was a .dll. When I hit F5 to run it, I get an error saying it can not find zonebuilder.exe in my MW2 directory.
![damn error](https://cloud.githubusercontent.com/assets/10711154/8735128/1a82924e-2bd4-11e5-91a0-6eea474a158e.png)

**Comment by ghost** [comment]
You are gonna need to create a separate issue for that (make sure you close this one). I'm sorry but I don't know the solution to this :(

**Comment by shit-ware** [comment]
Aww, alright. Thanks for your help earlier.

**Comment by ghost** [comment]
You're welcome!
