### ISSUE TITLE
Configuration system

### ISSUE THREAD

**Issue by ghost** [TheApadayo/zonebuilder#13]

**Comment by iAmThatMichael** [comment]
Er what?

**Comment by TheApadayo** [comment]
do care to explain

**Comment by ghost** [comment]
Implement a configuration system instead of using arguments for faster debugging instead of using the command line.

**Comment by momo5502** [comment]
How would that improve debugging? Attach those params to the debugger and it's fine. Imo this case exacly fits the purpose of comandline params, so why change it?

**Comment by ghost** [comment]
@momo5502 I agree with you if you debug it. However, it would be nice to use something like config.yml (there are yaml libraries for c++) instead of arguments for a release build.

**Comment by ghost** [comment]
@TheApadayo (unrelated question: do you think it's possible to make a standalone tool similar to zonebuilder without using IW4?)

**Comment by TheApadayo** [comment]
I'm planning on writing a scripting like system that would allow you to run different commands that would allow for batch like building system. And no. Zonebuilder depends on IW4 for its ability to load zones to get certain base assets such as shaders and techsets which cannot be customized (you wouldn't want to anyways)

**Comment by TheApadayo** [comment]
scripting works now... use the exec command.
