### ISSUE TITLE
Unable to find "ZoneBuilder.exe"

### ISSUE THREAD

**Issue by shit-ware** [TheApadayo/zonebuilder#14]
Continuation from a previous issue that I had opened. Everything compiles, but I only get a .dll and I do not get an .exe. When I hit F5 to run the program I get this:
![damn error](https://cloud.githubusercontent.com/assets/10711154/8735217/bf5eb6a8-2bd4-11e5-8d96-c1ec4eac6a47.png)

**Comment by shit-ware** [comment]
I just can't seem to use my eyes... I found the release. Nevermind. For those who are like me, it's under the "release" tab.

**Comment by TheApadayo** [comment]
for those who are still confused, you need the files included in the release (found here: https://github.com/TheApadayo/zonebuilder/releases) to run the project, even when building from source.
