### ISSUE TITLE
Compiling, Verifying, and Dumping Errors

### ISSUE THREAD

**Issue by FreeTheTech101** [TheApadayo/zonebuilder#4]
Although dumping never seemed to work in the older builds, in the current build, performing any actions will cause the program to crash on initializing IW4.

**Comment by TheApadayo** [comment]
Are you doing a verify? Because there is currently a hard coded debug break in that code so I can debug the code in IDA. Also can I get any more info about the crash

**Comment by FreeTheTech101** [comment]
Doing any of the actions result in an output of this:

http://prntscr.com/6blt7q

Edit: No crash log is generated, compiled on VS2013 with no edits.

**Comment by TheApadayo** [comment]
If you run the program from within visual studio with the debug command it should give more information about the crash.

**Comment by FreeTheTech101** [comment]
When running from VS it compiles fine, but from a .bat it is not.

**Comment by TheApadayo** [comment]
fixed
