### ISSUE TITLE
TracerData.cpp isn't included and hash_map is deprecated

### ISSUE THREAD

**Issue by iAmThatMichael** [TheApadayo/zonebuilder#6]
Eh decided to check out the development of ZB after you messaged me but didn't open the solution until now. The Git is missing the aforementioned CPP, commit it yo.
Also completely remove hash_map for unordered_map :)

IMG: http://puu.sh/gn49Z/584dc150fb.png

**Comment by TheApadayo** [comment]
Added the TracerData.cpp.
And hash_map isn't referenced anywhere in the code.
just "unordered_map" and "google/dense_hash_map"

**Comment by iAmThatMichael** [comment]
Exactly that, the dense_has_map is the problem. Using VS 2015 Preview and it won't let me compile it because of it :(

**Comment by TheApadayo** [comment]
fixed.
