### ISSUE TITLE
Describe XME/XAE/IWI formats in README.md

### ISSUE THREAD

**Issue by ghost** [TheApadayo/zonebuilder#9]

**Comment by TheApadayo** [comment]
I honestly don't know what is stored in the XME & XAE formats. They are produced in a different tool that wasn't written by me. IWI has been documented fairly well elsewhere.

**Comment by ghost** [comment]
Okay, but I think that this issue should be left open in case someone comes up with an approximate description of the mentioned formats.

**Comment by iAmThatMichael** [comment]
I'd just assume the XME/XAE are just the xmodel assets themselves dumped to a different format than the compiled format so then they can be reconverted into IW4 xmodel/xanim format.

**Comment by TheApadayo** [comment]
So basically its just a dump of data that we have no idea what it does other than the fact that it works.  The assets are so optimized that I doubt anyone will figure the data out any time soon.

**Comment by FreeTheTech101** [comment]
Well, XME's contain the name of the model, tags, and a list of materials, including the techsets they use. XAE's contain the name of the anim, tags (Including the hands and such),  their respective sounds (If it's a reload anim), as well as an termination word. (€?end). Now, there is a lot of other information I am not sure about that, but hell, it's a start.

Edit: Ah, yes, and XME's for WM only contain the following tags: tag_weapon, tag_brass, tag_clip and, tag_flash. Now, these are depending on the weapon itself. This is just a quick check to the IW3 WM, well the VM contains j_gun, j_bolt2, j_trigger, tag_acog, tag_ak47_mount, tag_brass, tag_clip, tag_flash, and tag_reflex_sight. But, the materials for both the VM and WM match in terms of the model itself, but, tags do not match as the WM does not have any tags. 

Edit 2: https://i.imgur.com/a8iXnfP.png
Blue = Tags
Yellow = Sounds
Red = End (Not sure of what)

**Comment by ghost** [comment]
@FreeTheTech101 Thanks a lot for the description of the formats!

**Comment by TheApadayo** [comment]
The format is much more complicated than that I'm afraid. I'm going to close this because the discussion here is mostly useless.
